ktor:
  deployment:
    port: $PORT:8080
  application:
    modules:
      - me.emyar.ffmpegutils.MainKtorKt.module
    dependencies:
      - me.emyar.ffmpegutils.services.LimitersKt.processingParallelismLimiter
      - me.emyar.ffmpegutils.services.CoroutineProcessService
      - me.emyar.ffmpegutils.services.FileCharsetDetectorService
      - me.emyar.ffmpegutils.services.PathsAbsoluterService
      - me.emyar.ffmpegutils.services.StreamsInfoService
      - me.emyar.ffmpegutils.services.audio.AudioNormalizationService
      - me.emyar.ffmpegutils.services.audio.SingleFileAudioNormalizationService
      - me.emyar.ffmpegutils.services.audio.BatchFilesAudioNormalizationService
      - me.emyar.ffmpegutils.services.KillerService
    config:
      limits:
        processingParallelism: $PARALLELISM:1
      defaultInPath: ${?DEFAULT_IN_PATH}
      defaultOutPath: ${?DEFAULT_OUT_PATH}
      ebuR128Config: $EBU_R128_CONFIG:I=-23:TP=-2:LRA=7
