ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }

  application {
    modules = [
      me.emyar.ffmpegutils.MainKtorKt.module
    ]

    dependencies = [
      me.emyar.ffmpegutils.services.LimitersKt.processingParallelismLimiter
      me.emyar.ffmpegutils.services.CoroutineProcessService
      me.emyar.ffmpegutils.services.FileCharsetDetectorService
      me.emyar.ffmpegutils.services.PathsAbsoluterService
      me.emyar.ffmpegutils.services.StreamsInfoService
      me.emyar.ffmpegutils.services.audio.AudioNormalizationService
      me.emyar.ffmpegutils.services.audio.SingleFileAudioNormalizationService
      me.emyar.ffmpegutils.services.audio.BatchFilesAudioNormalizationService
      me.emyar.ffmpegutils.services.KillerService
    ]

    config {
      limits {
        processingParallelism = 1
        processingParallelism = ${?PARALLELISM}
      }

      defaultInPath = ${?DEFAULT_IN_PATH}
      defaultOutPath = ${?DEFAULT_OUT_PATH}

      ebuR128Config = "I=-23:TP=-2:LRA=7"
      ebuR128Config = ${?EBU_R128_CONFIG}

      audioFormatOutConfig = "aac -profile:a aac_low -b:a 320k -ac 2 -ar 48000"
      audioFormatOutConfig = ${?AUDIO_FORMAT_OUT_CONFIG}
    }
  }
}
