ktor:
  deployment:
    port: 8080
  application:
    modules:
      - me.emyar.ffmpegutils.MainKtorKt.module
    dependencies:
      - me.emyar.ffmpegutils.LimitersKt.processingParallelismLimiter
      - me.emyar.ffmpegutils.audio.AudioNormalizationService
      - me.emyar.ffmpegutils.audio.SingleFileAudioNormalizationService
    config:
      limits:
        processingParallelism: 1
      defaultInPath: null
      defaultOutPath: null
      ebuR128Config: I=-23:TP=-2:LRA=7
